### ISSUE TITLE
Ping features reports 'error pinging: socket: permission denied' when running via Docker Compose

### ISSUE THREAD

**Issue by tacomilkshake** [Trugamr/wol#6]
I'm using the following docker-compose.yml on a Debian Bookworm 12 machine running Docker/Docker Compose:

```
services:
  wol:
    container_name: jamie-wol
    hostname: wol
    image: ghcr.io/trugamr/wol:latest
    command: serve
    network_mode: 'host'
    cap_add:
      - NET_RAW
    volumes:
      - ./config.yml:/etc/wol/config.yaml
    restart: unless-stopped
```

And upon running, the wol server is unable to ping my hosts, reporting:

```
2025/02/02 19:58:54 Error getting status for machine midnight: error pinging: socket: permission denied
```

I figured adding `cap_add: - NET_RAW` would fix, but it does not.
