### ISSUE TITLE
Feature Request: environment variable configuration support

### ISSUE THREAD

**Issue by kyoukaya** [Trugamr/wol#7]
I would like to have a docker compose setup without bind mounts for ease of portability. Something along the lines of this example:

```yaml
services:
  wol:
    image: ghcr.io/trugamr/wol
    command: serve
    network_mode: "host"
    # No volume binding required, but if present, would overwrite the CONFIG environment variable's value.
    # volumes:
      # - ./config.yaml:/etc/wol/config.yaml
    environment:
      CONFIG: |
        machines:
          - name: desktop
            mac: "00:11:22:33:44:55"
            ip: "192.168.1.100" # Optional, for status checking
          - name: server
            mac: "AA:BB:CC:DD:EE:FF"
            ip: "192.168.1.101" # Optional, for status checking
          server:
            listen: ":7777" # Optional, defaults to :7777
```

Would be happy to write the PR for it if you're fine with it.
